### ISSUE TITLE
Remove the constraint to build objects with an empty constructor only

### ISSUE THREAD

**Issue by lucassaldanha** [lucassaldanha/playdoh#12]
Playdoh only builds objects with an empty constructor. It would be nice to remove this constrain (is it possible?). Maybe we need more research on that.

**Comment by muditporwal** [comment]
Hi,
Could you evaluate my PR in regards to the same. I would like some help to suggest test cases that I might have missed also.

**Comment by lucassaldanha** [comment]
I think we have a good coverage in other scenarios. And you added the test for the scenario you fixed so it looks good to me.

**Comment by muditporwal** [comment]
Thanks :relieved:
